# Site settings
title: trash-fantastic
email: brianwedmond@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Revise. Rebuild. Repurpose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bedmond.github.io/trash-fantastic" # the base hostname & protocol for your site
twitter_username:
github_username:  

# Build settings
markdown: kramdown
